### ISSUE TITLE
doesn't work  - [I NEED INFORMATION]

### ISSUE THREAD

**Issue by Chunkf** [Alexander-Lancellott/MHGU-MHXX-HP-Overlay-For-Switch-Emulator#1]
doesn't work at all unlike it's 4U alternative. "MHGU running" but doesn't display anything

**Comment by Alexander-Lancellott** [comment]
Hi and sorry for the delay. I've tried several different things but haven't been able to replicate it. Could you give me more information? Which emulator and version are you using ? Which version of MHGU are you using, 1.0 or 1.4? What firmware version do you have installed on the emulator? Which version of Windows do you have, or is there anything else you think might be helpful?

**Comment by Alexander-Lancellott** [comment]
I'm closing it due to lack of interest and inactivity. If this happens to someone else, please report it with the corresponding information and I'll reopen it.

**Comment by MrR341-GER** [comment]
reopened this in #16
